(module basic.okm
        (extern $x :i32)
        (func $fib ((%a :i32)) -> (:i32)
          (region
            (block ^bb0 ()
              (%cond :i32 = (constant :i32 1) (lte %a 1))
              (br-cond %cond (^bb1) (^bb2)))
            (block ^bb1 ()
              (ret %a))
            (block ^bb2 ()
              (%b :i32 = (sub :i32 %a 1))
              (%c :i32 = (sub :i32 %a 2))
              (%d :i32 = (call $fib %b))
              (%e :i32 = (call $fib %c))
              (%f :i32 = (add :i32 %d %e))
              (ret %f)))))
